# Change these first
owner: lucasenlucas
# co-developer study buddy
repo: study-buddy-status

sites:
  - name: study buddy home
    url: https://offline.lucasmangroelal.nl
  - name: study buddy docs
    url: https://offline.lucasmangroelal.nl
  - name: study buddy dashboard
    url: https://offline.lucasmangroelal.nl

status-website:
  cname: offline.lucasmangroelal.nl

  logoUrl: https://github.com/lucasenlucas/lucascdn/blob/main/Scherm%C2%ADafbeelding%202025-10-06%20om%2016.35.57.png?raw=true
  name: study buddy status
  introTitle: ""
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: home
      href: /
